# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Artspace2.0' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Artspace2.0
    pod 'Firebase/Analytics'

  target 'Artspace2.0Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
